=== charanshashi/internal/1,9-A,12/motorbike.dtd
<!ELEMENT catalog (motorbike*)>

<!ELEMENT motorbike (make, model, year, colour, engine, chasisNumber, accessories)>

<!ELEMENT make (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT colour (#PCDATA)>
<!ELEMENT engine (engineNumber, numberOfCylinders, typeOfFuel)>
<!ELEMENT chasisNumber (#PCDATA)>
<!ELEMENT accessories EMPTY>

<!ELEMENT engineNumber (#PCDATA)>
<!ELEMENT numberOfCylinders (#PCDATA)>
<!ELEMENT typeOfFuel (#PCDATA)>

<!ATTLIST accessories
    discBrake (yes | no) #REQUIRED
    autoStart (yes | no) #REQUIRED
    radio (yes | no) #REQUIRED
>

=== charanshashi/internal/1,9-A,12/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "motorbike.dtd">
<catalog>
    <motorbike>
        <make>Honda</make>
        <model>CBR600RR</model>
        <year>2020</year>
        <colour>Red</colour>
        <engine>
            <engineNumber>ENG123456</engineNumber>
            <numberOfCylinders>4</numberOfCylinders>
            <typeOfFuel>Petrol</typeOfFuel>
        </engine>
        <chasisNumber>CHS123456</chasisNumber>
        <accessories discBrake="yes" autoStart="yes" radio="no" />
    </motorbike>
    <motorbike>
        <make>Yamaha</make>
        <model>YZF-R6</model>
        <year>2021</year>
        <colour>Blue</colour>
        <engine>
            <engineNumber>ENG654321</engineNumber>
            <numberOfCylinders>4</numberOfCylinders>
            <typeOfFuel>Petrol</typeOfFuel>
        </engine>
        <chasisNumber>CHS654321</chasisNumber>
        <accessories discBrake="yes" autoStart="no" radio="yes" />
    </motorbike>
</catalog>
